# Generated by Django 2.0.4 on 2018-05-31 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField(auto_now_add=True)),
                ('article_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текс коментария')),
                ('comments_date', models.DateTimeField(auto_now=True)),
                ('comments_article', models.ForeignKey(null=True, on_delete='', related_name='+', to='forum.Article')),
                ('comments_from', models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
