# Generated by Django 2.0.4 on 2018-05-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_likes',
        ),
    ]
