# Generated by Django 2.0.4 on 2018-05-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180531_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_from',
        ),
    ]
