# Generated by Django 2.0.4 on 2018-05-31 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_remove_comments_comments_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_from',
            field=models.ForeignKey(default=1, on_delete='', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
