# Generated by Django 2.0.4 on 2018-06-03 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anonim_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField()),
                ('nickname_message', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete='', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
