# Generated by Django 2.0.4 on 2018-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20180603_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonim_message',
            name='text_message',
            field=models.TextField(verbose_name='Раскажите свою историю'),
        ),
    ]
